# This workflow updates osos data every week

name: Update OSOS Data
on:

  # Run every Sunday night at 11pm Mountain Time (6am Monday UTC)
  schedule:
    - cron: "0 6 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - name: Checkout OSOS
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run the OSOS CLI
        run: |
          osos run --config ./osos_config.csv -v
          osos plot -m pypi_daily -y '{name} PyPI Downloads (cumulative)' -c -v

      - name: Commit and push
        run: |
          git config --global user.name 'RHammond2'
          git config --global user.email '13874373+RHammond2@users.noreply.github.com'
          git add ./data/*.csv
          git add ./plots/*.png
          git commit -m "update osos data and plots"
          git pull
          git push
